title: SAC2020 Conference
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
  Halifax, NS - Aug 12-14, 2020<br><br>
  Call for Papers (Coming Soon)<br>
  Local Information (Coming Soon)<br>
  Program (Coming Soon)<br><br>
  <a href="https://www.sacworkshop.org">Previous SACs</a> 
theme: jekyll-theme-minimal