title: SAC2020 Conference
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
  Selected Areas in Cryptography (SAC) 2020
  <br><br>
  Halifax, NS 
  <br><br>
  <a href="https://www.sacworkshop.org">Previous SACs</a> 
show_downloads: False
theme: jekyll-theme-minimal