title: SAC2020 Conference
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
  Halifax, NS - Aug 12-14, 2020<br><br>
  <b>Call for Papers</b> (Coming Soon)<br>
  <b>Local Information</b> (Coming Soon)<br>
  <b>Program</b> (Coming Soon)<br><br>
  <a href="https://www.sacworkshop.org">Previous SACs</a> 
theme: jekyll-theme-minimal