title: SAC2020 Conference
logo: "/images/sac2020.png?raw=true" # your photo (or logo) here
description: >
  Cyberweb - Oct 19-23, 2020<br><br>
  <a href="cfp.html"><b>Call for Papers</b></a><br>
  <a href="pc.html"><b>Program Committee</b></a><br>
  <b>Program</b> (Coming Soon!)<br><br>
  <a href="https://www.sacworkshop.org">Previous SACs</a> 
theme: jekyll-theme-minimal
